// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manually define the sidebar content, including the HTML link
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'}, // This keeps your autogenerated sidebar

    // Add a link to your HTML file
    {
      type: 'link',
      label: 'Practise Questions',  // This will be the text shown in the sidebar
      href: 'static/oa_doc/dsa.html',  // Path to your HTML file
    },
  ],
};

export default sidebars;
