// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Define the sidebar with a main item and a nested category
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},  // Keep the autogenerated items

    // Main sidebar item
    {
      type: 'category',
      label: 'Practice Questions',
      items: [
        // Nested sidebar under Practice Questions
        {
          type: 'link',
          label: 'DSA Questions',
          href: '/dsa.html'  // Path to your HTML file
        }
          
          ],
        },
      ],
    };

export default sidebars;
