/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  autogeneratedSidebar: [{ type: "autogenerated", dirName: "." }],

  // Custom Sidebar
  practiceSidebar: [
    {
      type: "category",
      label: "Practice for your next OA",
      items: [
        {
          type:"category",
          label:"Data Structure and Algorithm",
          items:[
            "practice-for-OA/DSA/ArraysAndMap",
            "practice-for-OA/DSA/LinkedList",
            "practice-for-OA/DSA/StackAndQueues",
            "practice-for-OA/DSA/Strings",
            "practice-for-OA/DSA/Trees",
            "practice-for-OA/DSA/Others",
          ]
        },
        "practice-for-OA/DSA",
        "practice-for-OA/OOPs",
        "practice-for-OA/SQL",
        "practice-for-OA/REASONING",
        "practice-for-OA/OS",
        "practice-for-OA/CODING",
      ],
    },
  ]
};

export default sidebars;
